-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- CREATE DATABASE tnff;

DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

-- Table Definition ----------------------------------------------

CREATE TABLE tnff_films (
    id SERIAL PRIMARY KEY,
    title text,
    tnff_year text,
    location text,
    category text,
    release_date text,
    duration_mins integer,
    language text,
    director text,
    producer text,
    synopsis text,
    director_bio text,
    film_img_url text,
    director_img_url text,
    other_info text
);

COPY tnff_films FROM '/data/tnff_films.csv' DELIMITER ',' CSV HEADER;
-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX tnff_films_pkey ON tnff_films(id int4_ops);
