name: End-to-end tests
on: [push]
jobs:
  eslint:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.8'
      - run: npm install
      - name: Lint javscript code
        run: npm run lint